### ISSUE TITLE
iphone issue 

### ISSUE THREAD

**Issue by patel-pragnesh** [TheSmiths-Widgets/ts.photographer#1]
in iphone not work ,also animation error when run project 

nothing happen

**Comment by KtorZ** [comment]
Could you please describe a bit more your issue so that we can help?

**Comment by patel-pragnesh** [comment]
ts.photographer: The animation 'D' does not exist.
[ERROR] :  ts.photographer: The animation 'I' does not exist.
[ERROR] :  ts.photographer: The animation 'S' does not exist.
[ERROR] :  ts.photographer: The animation 'C' does not exist.
[ERROR] :  ts.photographer: The animation 'A' does not exist.
[ERROR] :  ts.photographer: The animation 'R' does not exist.
[ERROR] :  ts.photographer: The animation 'D' does not exist.
[ERROR] :  ts.photographer: The animation '_' does not exist.
[ERROR] :  ts.photographer: The animation 'S' does not exist.
[ERROR] :  ts.photographer: The animation 'W' does not exist.
[ERROR] :  ts.photographer: The animation 'I' does not exist.
[ERROR] :  ts.photographer: The animation 'P' does not exist.
[ERROR] :  ts.photographer: The animation 'E' does not exist.
[ERROR] :  ts.photographer: The animation '_' does not exist.
[ERROR] :  ts.photographer: The animation 'H' does not exist.
[ERROR] :  ts.photographer: The animation 'O' does not exist.
[ERROR] :  ts.photographer: The animation 'R' does not exist.
[ERROR] :  ts.photographer: The animation 'I' does not exist.
[ERROR] :  ts.photographer: The animation 'Z' does not exist.
[ERROR] :  ts.photographer: The animation 'O' does not exist.
[ERROR] :  ts.photographer: The animation 'N' does not exist.
[ERROR] :  ts.photographer: The animation 'T' does not exist.
[ERROR] :  ts.photographer: The animation 'A' does not exist.
[ERROR] :  ts.photographer: The animation 'L' does not exist.

ts.photographer: [object Object]
[WARN] :   New layout set while view [object TiUIActivityIndicator] animating: Will relayout after animation. 

tested on Devices :iphone 4s ,ios8.3

**Comment by KtorZ** [comment]
Please, do this :

``` javascript
$.photographer.init({
    animations: [ $.photographer.DISCARD_SWIPE_HORIZONTAL ]
});
```

not this :

``` javascript
$.photographer.init({
    animations: $.photographer.DISCARD_SWIPE_HORIZONTAL
});
```

By the by, would you mind looking at the documentation before opening an issue? 

Thanks.
